[package]
name = "h3s-auth"
description = "RBAC, ServiceAccount tokens, NodeRestriction, bootstrap certs"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
k8s-openapi.workspace = true
x509-parser = "0.18.1"
thiserror = "2"
sha2 = "0.10.9"
subtle = "2.6.1"
getrandom = "0.4"

[dev-dependencies]
h3s-certs = { path = "../h3s-certs" }
tempfile = "3"
serde_json = "1"
