[package]
name = "h3s-certs"
description = "Cluster PKI"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
rcgen = { version = "0.14.10", default-features = false, features = ["aws_lc_rs", "pem", "x509-parser", "zeroize"] }
rustls.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
time = "0.3"
x509-parser = { version = "0.18.1", features = ["verify-aws"] }
tempfile = "3"
libc = "0.2"
base64 = "0.22"

[dev-dependencies]
tokio.workspace = true
tokio-rustls = "0.26.5"
