[package]
name = "h3s"
description = "Hedronetes multicall binary (server / agent)"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "h3s"
path = "src/main.rs"

[dependencies]
clap.workspace = true
rustls.workspace = true
tokio.workspace = true
h3s-apiserver = { path = "../h3s-apiserver" }
h3s-certs = { path = "../h3s-certs" }
h3s-storage = { path = "../h3s-storage" }
tempfile = "3"
h3s-controllers = { path = "../h3s-controllers" }

h3s-auth = { path = "../h3s-auth" }
h3s-kubelet = { path = "../h3s-kubelet" }
